spring.application.name=square_games
spring.messages.basename=message

game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.taquin.default-player-count=1
game.taquin.default-board-size=4

game.connect4.default-player-count=2
game.connect4.default-board-size=7

spring.datasource.url=jdbc:postgresql://localhost:5432/square_gamesdb
spring.datasource.username=mouna
spring.datasource.password=mouna
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always